"""
rag/generator.py
Składanie odpowiedzi z pobranych fragmentów dokumentów.
"""

from __future__ import annotations
import requests
import json
import os
import re
from .retriever import RetrievedChunk
from config.settings import SIMILARITY_THRESHOLD


# ── WYNIK ZAPYTANIA ───────────────────────────────────────────────────────────
class QueryResult:
    """
    Rezultat pojedynczego zapytania do systemu RAG.
    text == None oznacza "Nie znaleziono informacji w dokumentacji".
    """

    def __init__(self, text: str | None, sources: list[RetrievedChunk]):
        self.text    = text
        self.sources = sources

    def found(self) -> bool:
        return self.text is not None

    def to_dict(self) -> dict:
        """Konwertuje do formatu oczekiwanego przez UI."""
        return {
            "text": self.text,
            "sources": [
                {
                    "file":  s.file,
                    "chunk": s.chunk,
                    "score": s.score,
                    "text":  s.text,
                }
                for s in self.sources
            ],
        }


# ── GENERATOR ─────────────────────────────────────────────────────────────────
def generate_answer(question: str, chunks: list[RetrievedChunk]) -> QueryResult:
    """Składa odpowiedź na podstawie listy pobranych fragmentów."""
    valid = _get_valid_chunks(chunks)
    if not valid:
        return QueryResult(text=None, sources=[])

    answer = _call_ollama(question, valid)
    return QueryResult(text=answer, sources=valid)


def _get_valid_chunks(chunks: list[RetrievedChunk]) -> list[RetrievedChunk]:
    """Filtruje fragmenty według progu podobieństwa."""
    valid = [c for c in chunks if c.score >= SIMILARITY_THRESHOLD]
    if not valid:
        # Fallback do progu 0.20 — pozwala na szersze wyszukiwanie przy zapytaniach PL->EN.
        valid = [c for c in chunks[:5] if c.score > 0.20]
    return valid


# ── SANITYZACJA WYJŚCIA ───────────────────────────────────────────────────────

# Frazy techniczne UI — model nie powinien ich nigdy generować.
_TEXT_TRIGGERS = [
    "Odpowiedź wygenerowana przez",
    "Answer generated by",
    "🤖 ODPOWIEDŹ Z LLM",
    "🤖 LLM ANSWER",
    "💡",
    "DOKUMENTACJA:",
    "SYSTEM:",
    "PYTANIE:",
    "USER:",
    "ASSISTANT:",
]

# Tagi HTML, przy których natychmiast ucinamy tekst.
# Model nie powinien generować żadnego kodu HTML.
_HTML_TAGS = ["<", "&lt;"]


def _first_html_tag_index(text: str) -> int:
    """Zwraca pozycję pierwszego tagu HTML lub -1 jeśli brak."""
    idx = -1
    for tag in _HTML_TAGS:
        pos = text.find(tag)
        if pos != -1 and (idx == -1 or pos < idx):
            idx = pos
    return idx


def sanitize_output(text: str) -> str:
    """
    Usuwa HTML i halucynowane fragmenty UI z odpowiedzi modelu.

    Strategia cięcia (w kolejności):
    1. Odkoduj HTML-escape (&lt; → <) — Ollama czasem koduje tagi zamiast je emitować.
    2. Utnij przy pierwszym tagu HTML — model nie powinien nigdy generować HTML.
    3. Utnij przy pierwszym triggerze tekstowym (stopka UI, nagłówki sekcji).
    4. Usuń ewentualne resztki tagów regexem jako ostatnią linię obrony.
    """
    if not text:
        return ""

    # 1. Odkodowanie HTML-escape — dopiero po tym tagi są wykrywalne jednym kodem
    text = text.replace("&lt;", "<").replace("&gt;", ">").replace("&amp;", "&")

    # 2. Cięcie przy pierwszym tagu HTML
    html_idx = _first_html_tag_index(text)
    if html_idx != -1:
        text = text[:html_idx]

    # 3. Cięcie przy triggerach tekstowych
    for trigger in _TEXT_TRIGGERS:
        idx = text.find(trigger)
        if idx != -1:
            text = text[:idx]

    # 4. Regex jako ostatnia linia obrony — usuwa resztki otwartych tagów
    text = re.sub(r'<[^>]*?>', '', text, flags=re.DOTALL)
    text = re.sub(r'<[^>]*$', '', text)

    return text.strip()


# ── PROMPT ────────────────────────────────────────────────────────────────────

def _extract_allowed_titles(chunks: list[RetrievedChunk]) -> str:
    """Buduje jawną listę tytułów filmów wyłącznie z dostarczonych chunków."""
    seen: set[str] = set()
    lines: list[str] = []
    for c in chunks:
        title = (
            c.file
            .replace("_", " ")
            .replace(".txt", "")
            .strip()
            .title()
        )
        if title not in seen:
            seen.add(title)
            lines.append(f"- {title}")
    return "\n".join(lines)


def _get_ollama_prompt(question: str, chunks: list[RetrievedChunk]) -> str:
    """
    Generuje prompt z jawną listą dozwolonych tytułów i rygorystycznymi zasadami.
    """
    context = "\n\n".join(
        f"[FRAGMENT {i + 1}]\n{c.text}" for i, c in enumerate(chunks)
    )
    allowed_titles = _extract_allowed_titles(chunks)

    return f"""Jesteś asystentem filmowym. Odpowiadasz WYŁĄCZNIE na podstawie poniższej bazy.

FILMY DOZWOLONE — jedyne tytuły, które możesz wymienić:
{allowed_titles}

FRAGMENTY Z BAZY:
{context}

PYTANIE: {question}

ZASADY BEZWZGLĘDNE:
1. Wymieniaj TYLKO filmy z listy "FILMY DOZWOLONE". Żadnych innych.
2. Nie uzupełniaj odpowiedzi własną wiedzą. Jeśli film nie jest na liście, nie istnieje.
3. Wybierz filmy z listy, które najlepiej pasują do nastroju lub tematyki pytania.
4. Odpowiadaj czystym tekstem po polsku. Zero tagów HTML, kodu, emoji ani komentarzy.
5. Nie dodawaj żadnej stopki, podpisu ani informacji o modelu.

ODPOWIEDŹ:"""


# ── STOP-SEKWENCJE ────────────────────────────────────────────────────────────

_STOP_SEQUENCES = [
    "<", "&lt;",
    "<!--", "```",
    "💡", "🤖",
    "DOKUMENTACJA:", "SYSTEM:", "PYTANIE:", "USER:", "ASSISTANT:",
]

_OLLAMA_OPTIONS = {
    "temperature": 0.0,
    "top_p":       0.9,
    "top_k":       40,
    "stop":        _STOP_SEQUENCES,
}


# ── WYWOŁANIA OLLAMY ──────────────────────────────────────────────────────────

def _call_ollama(question: str, chunks: list[RetrievedChunk]) -> str:
    """Wysyła zapytanie do lokalnej Ollamy (tryb niestrumieniowy)."""
    url   = os.getenv("OLLAMA_API_URL", "http://localhost:11434")
    model = os.getenv("OLLAMA_MODEL", "neural-chat")
    prompt = _get_ollama_prompt(question, chunks)

    try:
        res = requests.post(
            f"{url}/api/generate",
            json={
                "model":   model,
                "prompt":  prompt,
                "stream":  False,
                "options": _OLLAMA_OPTIONS,
            },
            timeout=90,
        )
        if res.status_code == 200:
            raw = res.json().get("response", "").strip()
            return sanitize_output(raw)
        return "Błąd komunikacji z modelem LLM."
    except Exception as e:
        return f"Błąd: {str(e)}"


def _should_stop_stream(accumulated: str) -> bool:
    """
    Sprawdza czy strumieniowanie powinno zostać przerwane.

    Sprawdzamy narastający tekst PO odkodowaniu HTML-escape — dzięki temu
    &lt;div i <div są traktowane identycznie, nawet gdy Ollama nie
    zatrzymała się na stop-sekwencji.
    """
    decoded = accumulated.replace("&lt;", "<").replace("&gt;", ">")

    # Wykrycie tagu HTML — model nie ma prawa generować HTML
    if _first_html_tag_index(decoded) != -1:
        return True

    # Wykrycie triggera tekstowego (stopka UI, nagłówki sekcji)
    if any(trigger in decoded for trigger in _TEXT_TRIGGERS):
        return True

    return False


def call_ollama_stream(question: str, chunks: list[RetrievedChunk]):
    """
    Generator tokenów z Ollamy (tryb strumieniowy).

    Po każdym tokenie sprawdzamy narastający tekst. Jeśli wykryto HTML
    lub frazę stopki UI, generator kończy pracę natychmiast — zanim UI
    zdąży wyrenderować nieprawidłową zawartość.
    """
    url   = os.getenv("OLLAMA_API_URL", "http://localhost:11434")
    model = os.getenv("OLLAMA_MODEL", "neural-chat")
    prompt = _get_ollama_prompt(question, chunks)

    accumulated = ""

    try:
        res = requests.post(
            f"{url}/api/generate",
            json={
                "model":   model,
                "prompt":  prompt,
                "stream":  True,
                "options": _OLLAMA_OPTIONS,
            },
            stream=True,
            timeout=90,
        )
        for line in res.iter_lines():
            if not line:
                continue

            chunk_data = json.loads(line.decode("utf-8"))
            token = chunk_data.get("response", "")
            accumulated += token

            # Wczesne zatrzymanie — sprawdzamy PRZED yieldem,
            # żeby zanieczyszczony token nigdy nie trafił do UI.
            if _should_stop_stream(accumulated):
                break

            yield token

            if chunk_data.get("done"):
                break

    except Exception as e:
        yield f" Błąd: {str(e)}"


# ── FALLBACK: SKŁADANIE Z CHUNKÓW (bez LLM) ───────────────────────────────────

def _assemble_from_chunks(question: str, chunks: list[RetrievedChunk]) -> str:
    """Buduje czytelną odpowiedź przez złożenie tekstów fragmentów."""
    titles = ", ".join(
        c.file.replace("_", " ").replace(".txt", "").title()
        for c in chunks
    )
    return (
        f"Na podstawie dostępnej dokumentacji filmowej znaleziono "
        f"{len(chunks)} powiązanych fragmentów dotyczących pytania: "
        f"*{question}*\n\n"
        f"**Powiązane filmy:** {titles}"
    )


# ── WARIANT B: SZKIELET LLM (OpenAI) ─────────────────────────────────────────
# def _call_llm(question: str, chunks: list[RetrievedChunk]) -> str:
#     import openai
#     context = "\n\n".join(f"[{c.file} #{c.chunk}]\n{c.text}" for c in chunks)
#     prompt  = (
#         f"Odpowiedz na pytanie wyłącznie na podstawie poniższej dokumentacji.\n"
#         f"Jeśli odpowiedź nie wynika z dokumentacji, napisz: "
#         f"'Nie znaleziono informacji w dokumentacji'.\n\n"
#         f"DOKUMENTACJA:\n{context}\n\n"
#         f"PYTANIE: {question}\n\nODPOWIEDŹ:"
#     )
#     response = openai.chat.completions.create(
#         model="gpt-4o-mini",
#         messages=[{"role": "user", "content": prompt}],
#         max_tokens=512,
#     )
#     return response.choices[0].message.content.strip()